language: objective-c
osx_image: xcode10.0
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Arithmosophi.xcodeproj
  - IOS_SDK=iphonesimulator12.0
  - MACOS_SDK=macosx10.13
  matrix:
    - DESTINATION="OS=12.0,name=iPhone 8" SCHEME="Arithmosophi" SDK="$IOS_SDK" RUN_TESTS=""
    - DESTINATION="arch=x86_64" SCHEME="ArithmosophiOSX" SDK="$MACOS_SDK" RUN_TESTS="YES"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
